// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYBVktU50TpL60ifx-7iIXuoXsxknhLBk',
    appId: '1:794752055168:web:bd9ae522aabe3b6b44f365',
    messagingSenderId: '794752055168',
    projectId: 'messz-c77b8',
    authDomain: 'messz-c77b8.firebaseapp.com',
    storageBucket: 'messz-c77b8.appspot.com',
    measurementId: 'G-HP4MK3X9RF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH7sfMCJpn86yB2C77JqzNgaXCMF_YsNQ',
    appId: '1:794752055168:android:74a48697616e32db44f365',
    messagingSenderId: '794752055168',
    projectId: 'messz-c77b8',
    storageBucket: 'messz-c77b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz8aW3jSNlWHY28SyP0nQvCnCHFMvjByE',
    appId: '1:794752055168:ios:e995174754828eda44f365',
    messagingSenderId: '794752055168',
    projectId: 'messz-c77b8',
    storageBucket: 'messz-c77b8.appspot.com',
    iosBundleId: 'com.example.messapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz8aW3jSNlWHY28SyP0nQvCnCHFMvjByE',
    appId: '1:794752055168:ios:e995174754828eda44f365',
    messagingSenderId: '794752055168',
    projectId: 'messz-c77b8',
    storageBucket: 'messz-c77b8.appspot.com',
    iosBundleId: 'com.example.messapp',
  );
}
